# Configuração SPM para Jaeger 1.x

# Exporters: onde os spans e métricas serão enviados
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

# Connectors: convertem spans em métricas RED
connectors:
  spanmetrics:
    dimensions:
      - name: service.name
      - name: span.name
        rename_to: operation
      - name: span.kind
      - name: status.code
    histogram:
      unit: ms
      buckets: [1, 2, 5, 10, 25, 50, 75, 100, 250, 500, 1000, 2500, 5000, 10000]

# Configuração do service pipeline
service:
  extensions: [jaeger_storage]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [spanmetrics]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
  telemetry:
    logs:
      level: debug

# Extensões e configuração de armazenamento
extensions:
  jaeger_storage:
    backends:
      default:
        type: memory
    metric_backends:
      default:
        prometheus:
          endpoint: "http://prometheus:9090"
          normalize_calls: true
          normalize_duration: true