services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: unless-stopped
    command:
      - --sql_mode=NO_ENGINE_SUBSTITUTION
      - --innodb-flush-method=O_DIRECT
      - --innodb-use-native-aio=0
      - --default-authentication-plugin=mysql_native_password
      - --max_connections=500
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=ym-chatbot
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=dbpassword
      - MARIADB_AUTO_UPGRADE=1
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"   # UI
      - "14250:14250"   # gRPC collector
      - "14268:14268"   # HTTP collector
      - "14269:14269"   # Admin port
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    volumes:
      - ./config-spm.yaml:/etc/jaeger/config-spm.yaml
    command: ["--config-file=/etc/jaeger/config-spm.yaml"]
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:16686"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network

  worker_send_message:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    volumes:
      - "./storage:/app/storage"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/ym-chatbot?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=30000&socketTimeout=60000
      - SPRING_RABBITMQ_TEMPLATE_RECEIVE_TIMEOUT=30000
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpassword
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_CACHE_CHANNEL_SIZE=25
      - SPRING_RABBITMQ_REQUESTED_HEARTBEAT=60
      - SCRIPT_RATE_LIMIT_IN_SECONDS=50000
      - SCRIPT_RATE_LIMIT_IN_MINUTES=1000000
      - WORKER_SEND_MESSAGE_REPLICAS=22
      - UPDATE_STATUS_CONCURRENT_CONSUMERS=19
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Xms512m -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError
    networks:
      - app_network
    deploy:
      mode: replicated
      replicas: ${WORKER_SEND_MESSAGE_REPLICAS:-22}
      resources:
        limits:
          cpus: '2'
          memory: 2048M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 180s

networks:
  app_network:
    name: app_network

volumes:
  rabbitmq_data:
  mariadb_data:
