spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:ym-chatbot}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:dbuser}
    password: ${DB_PASSWORD:dbpassword}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

  rabbitmq:
    host: ${AMQP_HOST:localhost}
    port: ${AMQP_PORT:5672}
    username: ${AMQP_USERNAME:guest}
    password: ${AMQP_PASSWORD:guest}
    virtual-host: ${AMQP_VHOST:/}
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 50
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          max-interval: 10000ms
          multiplier: 2.0

facebook:
  client:
    id: ${FACEBOOK_CLIENT_ID:your_app_id}
    secret: ${FACEBOOK_CLIENT_SECRET:your_app_secret}
    refresh-token: ${FACEBOOK_REFRESH_TOKEN:your_long_lived_token}
  token:
    cacheMinutes: ${FACEBOOK_TOKEN_CACHE_MINUTES:55}    # Token cache time in minutes
    retryMax: ${FACEBOOK_TOKEN_RETRY_MAX:3}             # Maximum token refresh attempts
    retryDelay: ${FACEBOOK_TOKEN_RETRY_DELAY:1000}      # Initial delay between token refresh attempts (ms)
  rate:
    limit: ${FACEBOOK_API_RATE_LIMIT:10}              # API call rate limit
    interval: ${FACEBOOK_API_RATE_INTERVAL:1}         # Interval in seconds for rate limiting

application:
  rate-limit:
    script:
      seconds: ${SCRIPT_RATE_LIMIT_IN_SECONDS:10000}
      minutes: ${SCRIPT_RATE_LIMIT_IN_MINUTES:600000}

  worker:
    send-message:
      replicas: ${WORKER_SEND_MESSAGE_REPLICAS:10}
      scheduled-fetch-limit: ${WORKER_SCHEDULED_FETCH_LIMIT:10}
      enable-campaign-locking: ${ENABLE_CAMPAIGN_LOCKING:true}
      processed-by: ${PROCESSED_BY:java-ms-v2}
    update-status:
      concurrent-consumers: ${UPDATE_STATUS_CONCURRENT_CONSUMERS:20}

server:
  port: 8080
